name: equatable_gen
description: Automatically creates 'props' getters for classes using the equatable package.
version: 1.0.0
homepage: https://github.com/mrgnhnt96/equatable_gen/issues
issue_tracker: https://github.com/mrgnhnt96/equatable_gen/issues/issues

funding:
  - https://github.com/sponsors/mrgnhnt96

topics:
  - equatable
  - equality
  - equals
  - props
  - generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  analyzer: ">=5.0.0 <8.0.0"
  equatable_annotations: ">=0.1.0 <1.0.0"
  build: ^2.4.1
  code_builder: ^4.8.0
  change_case: ^2.2.0
  dart_style: ">=3.0.0 <4.0.0"
  meta: ">=1.0.0 <2.0.0"
  source_gen: ">=1.4.0 <3.0.0"
  path: ">=1.0.0 <2.0.0"
  source_span: ^1.10.0

dev_dependencies:
  build_runner: ^2.4.7
  build_test: ^2.2.3
  equatable: ^2.0.5
  generator_test: ^0.4.1
  lints: ^3.0.0
  test: ^1.24.9
