name: equatable_annotations
description: Provides annotations for the 'equatable_gen' code generator, used with the 'equatable' package
version: 1.0.0
homepage: https://github.com/mrgnhnt96/equatable_gen/issues
issue_tracker: https://github.com/mrgnhnt96/equatable_gen/issues/issues

funding:
  - https://github.com/sponsors/mrgnhnt96

topics:
  - equatable
  - equality
  - equals
  - props
  - generator

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  meta: ^1.9.1

dev_dependencies:
  equatable: ^2.0.5
  lints: ">=2.1.1 <4.0.0"
  test: ^1.21.5
